# This is a config for E2B sandbox template.
# You can use template ID (lzqf52cbmc3mbwp5wzth) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lzqf52cbmc3mbwp5wzth") # Sync sandbox
# sandbox = await AsyncSandbox.create("lzqf52cbmc3mbwp5wzth") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lzqf52cbmc3mbwp5wzth')

team_id = "d6157769-bee5-4f09-8086-5e2ff27c65d8"
dockerfile = "e2b.Dockerfile"
template_id = "lzqf52cbmc3mbwp5wzth"
name = "claude-code-python-sdk"
