# This is a config for E2B sandbox template.
# You can use template ID (9bvbonffx7m438p9bvkl) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("9bvbonffx7m438p9bvkl") # Sync sandbox
# sandbox = await AsyncSandbox.create("9bvbonffx7m438p9bvkl") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('9bvbonffx7m438p9bvkl')

team_id = "eea9ba56-1fa1-4011-8d34-c35487854aaa"
dockerfile = "e2b.Dockerfile"
template_id = "9bvbonffx7m438p9bvkl"
