name: Deploy E2B Template

on:
  push:
    branches: [ main ]
    paths:
      - 'e2b.Dockerfile'
      - '.github/workflows/deploy-e2b-template.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup E2B Environment
      uses: ./.github/actions/setup-e2b

    - name: Deploy template to E2B
      env:
        E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
      run: |
        e2b template build -c "/root/.jupyter/start-up.sh"
        e2b template publish -y
