name: PR Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'e2b.Dockerfile'
      - '.github/workflows/deploy-e2b-template.yml'
      - '.github/workflows/pr-validation.yml'

jobs:
  validate-docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup E2B Environment
      uses: ./.github/actions/setup-e2b

    - name: Test E2B template build
      env:
        E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
      run: |
        e2b template build -c "/root/.jupyter/start-up.sh"