name: PR Validation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'e2b.Dockerfile'
      - '.github/workflows/deploy-e2b-template.yml'
      - '.github/workflows/pr-validation.yml'

jobs:
  validate-docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install E2B CLI
      run: npm install -g @e2b/cli

    - name: Test E2B template build
      env:
        E2B_ACCESS_TOKEN: ${{ secrets.E2B_ACCESS_TOKEN }}
      run: |
        # test docker build
        e2b template build -c "/root/.jupyter/start-up.sh"